version: '3.3'

services:
   db:
     image: mysql:5.7
     hostname: mysqldb
     networks:
       vpcbr:
         ipv4_address: 12.10.0.6
     volumes:
       - db_data:/var/mysqldocker
     environment:
       MYSQL_ROOT_PASSWORD: root123
       MYSQL_DATABASE: dsdb
       MYSQL_USER: ds
       MYSQL_PASSWORD: ds
     healthcheck:
       test: "/usr/bin/mysql --user=root --password=root123 --execute \"SHOW DATABASES;\""
       timeout: 20s
       retries: 10
   app:
     depends_on:
       - db
     build: . 
     container_name: ds
     image: ds:latest
     hostname: dsapp
     networks:
       vpcbr:
         ipv4_address: 12.10.0.7
     restart: on-failure
     healthcheck:
       test: "mysql -h 12.10.0.6 --user=root --password=root123 --execute \"SHOW DATABASES;\""
       timeout: 20s
       retries: 10
volumes:
    db_data: {}
networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 12.10.0.0/24
