version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/mysqldocker
     environment:
       MYSQL_ROOT_PASSWORD: root123
       MYSQL_DATABASE: dsdb
       MYSQL_USER: ds
       MYSQL_PASSWORD: ds
     healthcheck:
       test: "/usr/bin/mysql --user=root --password=root123 --execute \"SHOW DATABASES;\""
       timeout: 20s
       retries: 10
   app:
     depends_on:
       - db
     image: dsapp:v1
     restart: on-failure
     healthcheck:
       test: "mysql -h db --user=root --password=root123 --execute \"SHOW DATABASES;\""
       timeout: 20s
       retries: 10
volumes:
    db_data: {}
